#!/usr/bin/env bash

#Dependencies
# -i3lock
# -Scrot
# -Imagmagick

SNAPSHOT_CMD="scrot $LOCK"
LOCK_FILE=/tmp/pixellock.png
[ ! "$BLUR" ] && BLUR=${1:-2}

if [ $BLUR -ge 0 ] || [ $BLUR -ge 1 ] ; then
SCALE1="10%" SCALE2="1000%"
elif [ $BLUR -ge 2 ] ; then
SCALE1="20%" SCALE2="500%"
elif [ $BLUR -ge 3 ]; then
SCALE1="40%" SCALE2="250%"
fi

$SNAPSHOT_CMD
convert $LOCK_FILE -scale $SCALE1 -scale $SCALE2 $LOCK_FILE
i3lock -i $LOCK_FILE
rm $LOCK_FILE
